# Generated by Django 3.2.6 on 2021-09-03 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20210823_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='id',
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='cart_id',
            field=models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bot.cart', verbose_name='cart_id'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='product_id',
            field=models.ManyToManyField(blank=True, to='bot.Product', verbose_name='Products'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_come', models.DateTimeField(auto_created=True, blank=True)),
                ('status', models.TextField(verbose_name=[('Поступил', 'Поступил'), ('Отправлен', 'Отправлен'), ('Ожидает', 'Ожидает')])),
                ('money', models.TextField(blank=True)),
                ('date_out', models.DateTimeField(blank=True)),
                ('delivery', models.CharField(default='Самовывоз', max_length=40)),
                ('products', models.ManyToManyField(to='bot.Product', verbose_name='order_products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.customer', verbose_name='customer_id')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
