# Generated by Django 3.2.6 on 2021-09-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20210903_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.TextField(verbose_name=[('Поступил', 'Поступил'), ('Отправлен', 'Отправлен'), ('Ожидает', 'Ожидает'), ('Оплачен', 'Оплачен')]),
        ),
    ]
